AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NovaMart Shipping Service

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    MemorySize: 256
    Environment:
      Variables:
        SHIPMENT_TABLE_NAME: shipments
        EVENT_BUS_NAME: default

Resources:
  ShippingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: novamart-shipping-handler
      CodeUri: ./
      Handler: src/shippingHandler.shippingHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: shipments
        - EventBridgePutEventsPolicy:
            EventBusName: default
      Events:
        PaymentSucceededRule:
          Type: EventBridgeRule
          Properties:
            EventBusName: default
            Pattern:
              source:
                - novamart.payment-service
              detail-type:
                - payment.succeeded

Outputs:
  ShippingFunctionArn:
    Description: Shipping Function ARN
    Value: !GetAtt ShippingFunction.Arn